alert("Error! Please enter a valid password")
alert("Welcome to JS Land...\rHappy coding!")
alert("Welcome to JS land...")
alert("Happy cooding!\rprevent this pagefrom creating additional dialogs.")
alert("Hello..I can run JS through my web browser console")